from src.platform_checker import PlatformChecker

LED_PIN = 2
AC_SENSOR_PIN = 34
STATUS_CHANGE_BUTTON_PIN = 25
RELAY_PIN = 32

AC_FREQUENCY = 50
AC_VOLTAGE = 220

ON = 1
OFF = 0

if PlatformChecker.is_device():
    HTTP_SERVER_HOST = '192.168.4.1'
    HTTP_SERVER_PORT = 80
else:
    HTTP_SERVER_HOST = 'localhost'
    HTTP_SERVER_PORT = 5001

HTTP_SERVER_MAX_CLIENTS = 1
HTTP_SERVER_PRINT_LOGS = True

REMOTE_API_URI = 'http://192.168.0.9:5000/api'

AP_SSID = 'ESP32'
AP_PASSWORD = 'micropython'

WIFI_CLIENT_MAX_CONNECTION_ATTEMPTS = 3
WIFI_CLIENT_DELAY_BETWEEN_ATTEMPTS = 5

SYNC_TIME_MAX_ATTEMPTS = 3
SYNC_TIME_DELAY_BETWEEN_ATTEMPTS = 3

MAX_MEASURES_BATCH_SIZE = 5

INTERVAL_TO_CHECK_NEXT_SCHEDULING_ACTION = 20  # Seconds
INTERVAL_TO_SEND_CURRENT_STATE = 10  # Seconds
